version: '3.3'

# Docker compose for local GRPC testing
services:
  nornir-deploy:
    build: .
    container_name: nornir-ci
    command: tail -F anything
    volumes:
      - ./:/usr/src/app:rw


volumes:
  pgdata: {}