
name: Compare configurations
on:
  push:
    branches: ["main"]
  
jobs:
   # Based on the branch gather the environment to deploy to..
  Identify-changes:
    runs-on: ["self-hosted"]
    name: test_flow
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: install requirements
        run: |
          pip3 install -r requirements.txt
      - name: Run nornir
        run: |
          cd ./nornir-image/app
          python3 configure_prod_devices.py
