
name: Compare configurations
on:
  push:
    branches: ["main"]
  
jobs:
   # Based on the branch gather the environment to deploy to..
  Identify-changes:
    runs-on: ["self-hosted"]
    name: Apply to Prod
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: install requirements
        run: |
          pip3 install -r requirements.txt
      - name: Apply service modified filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          base: "main"
          filters: |
            crqs:
              - add|modified : app/crq_configs/**
  
      - name: Run nornir
        if: ${{steps.filter.outputs.crqs_files != '' }}
        run: |
          changed_configs='${{steps.filter.outputs.crqs_files}}'
          cd app
          python3 configure_prod_devices.py --no_dry_run --list $changed_configs