
name: Compare configurations
on:
  push:
    branches: ["main"]
  
jobs:
   # Based on the branch gather the environment to deploy to
  Identify-MS:
    runs-on: ["self-hosted"]
    name: test_flow
    steps:
      - name: Set Value Based on Branch
        id: set_value
        run: |
          echo "test"